[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"

# Handle SPA routing for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Enable HTTPS by default
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.googleapis.com https://*.firebaseio.com https://*.firebasedatabase.app https://*.firebase.com wss://*.firebaseio.com wss://*.firebasedatabase.app https://firebaseinstallations.googleapis.com https://identitytoolkit.googleapis.com https://*.cloudinary.com https://*.google.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.firebaseapp.com https://*.firebasedatabase.app https://*.googleapis.com https://*.gstatic.com https://*.google.com https://apis.google.com; script-src-elem 'self' 'unsafe-inline' 'unsafe-eval' https://*.firebaseapp.com https://*.firebasedatabase.app https://*.googleapis.com https://*.gstatic.com https://*.google.com https://apis.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; img-src 'self' data: blob: https://*.googleapis.com https://*.gstatic.com https://*.firebase.com https://*.firebasedatabase.app https://*.cloudinary.com; frame-src https://*.firebaseapp.com https://*.google.com https://apis.google.com; object-src 'none'; worker-src 'self' blob:;" 